version: "3.8"
services:
  kong:
    image: kong:3.0.0
    container_name: kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_PROXY_LISTEN: "0.0.0.0:8000, 0.0.0.0:8443 ssl"
    ports:
      - "8000:8000"   # Kong proxy (http)
      - "8443:8443"   # Kong proxy (https)
      - "8001:8001"   # Kong admin
    volumes:
      - ./kong.yml:/kong/kong.yml:ro
      - ./keys/jwks.json:/kong/jwks.json:ro  # optional (fallback JWKS)
    depends_on:
      - mock-catalog

  nginx:
    image: nginx:1.25
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - kong

  mock-catalog:
    image: hashicorp/http-echo:latest
    container_name: mock-catalog
    command: ["-text", "{\"service\":\"catalog\",\"ok\":true}"]
    ports:
      - "5678:5678"
